### ISSUE TITLE
Swap touchpads hotkey activation

### ISSUE THREAD

**Issue by enroag** [MERLev/reVita#1]
First I want to thank you for your great work and contribution.

Since my rear touchpad is not working, I am using the functionality Swap touchpads to play games like Tearway. And this is working for the first time, all the previous plugins I have tried were not working or crashing when activating them.  This is more a feature request, would be possible to press a combo of keys to activate/deactivate the Swap touchpads functionality? As a workaround, I expected that creating a profile with this setting and activating/deactivating the plugin when playing will do the same but it looks like once the buttons have been remapped they stay like that the whole time.

**Comment by MERLev** [comment]
It's already there - but not as a hotkey though. 
Just create new remap rule: Button -> (select buttons) -> reVita options -> Swap touchpads.
You may want to save it as Global Default profile (Profile -> Profile Management -> Save as Global default), so it would be present in all new profiles created by default.

**Comment by enroag** [comment]
Thanks for the feedback, I just tried and it works very well.
