### ISSUE TITLE
When Power On from Off state, it boot until warning screen then power off back

### ISSUE THREAD

**Issue by jasonkhoo87** [MERLev/reVita#16]
As mentioned in title, I am facing such issue, tried several times same issue.

I need to press R and L trigger then power on to bypass the plugins and it boot well.

I am not sure what log needed.

**Comment by MERLev** [comment]
You can post your FW version and tai config. Most likely this is caused by unsupported FW or plugin incompatibility.

**Comment by jasonkhoo87** [comment]
Sorry late reply, I found out the culprit. It cause when I use udcd plugin with reVita.
