### ISSUE TITLE
Turning off the Ps vita/Desligando a Ps Vita

### ISSUE THREAD

**Issue by CoolWillBR** [MERLev/reVita#23]
hello i have ps vita slim and i have a problem, the problem is that when i open the menu and go to close the menu it turns ps vita off, i was wondering why this is happening, i want to use the ps3 control to use reartouch/Olá eu tenho a ps vita slim e tenho um problema, o problema é que quando abro o menu e vou fechar o menu desliga a ps vita, queria saber porque isso está acontecendo, eu quero usar o controle da ps3 pra usar o reartouch

**Comment by MERLev** [comment]
Most likely you have installed ds34vita too.
Most likely, you also used autoplugin.
Pls, update both plugins to latest versions from github pages, this should fix your issue.

**Comment by CoolWillBR** [comment]
thanks for answering, look I did something, uninstalled the ds34vita plugin and others, and it worked but the only thing that doesn't go well is that it doesn't map the L2 and R2 button for reartouch, can you do an update? I await your answer, good night ;)/obrigado por responder, olha eu fiz uma coisa desinstalei o plugin do ds34vita e outros, e deu certo mas unica coisa que não bate bem é que não deixa mapear o botão L2 e R2 pra reartouch, você pode fazer um update? Aguardo tua resposta, boa noite ;)

**Comment by CoolWillBR** [comment]
bem, eu consegui remapear mas não sei como, bem eu vou explicar: não sabia que tinha o botão [  ] para selecionar, mas consegui, os outros nem por isso, como por exemplo o Remap 2.0.2 não tava deixando usar o botão L2 e R2, mas testei e consegui usar o botão L2 e R2 nele no Remap 2.0.2, mas o plugin não tava deixando eu usar o botão L1 e R1, fui tentai denovo no seu plugin no ReVita, e deu certo, sabes vou fazer um video de tutorial e mostrar no YouTube, não se preocupe que vou dizer que foi vc que criou, muito obrigado por fazer este plugin, Ah e já agora eu vou fazer um video em Portugues, sinta-se livre pegar o meu video e traduzir em inglês/well, i managed to remap but i don't know how, well i'll explain: i didn't know i had the [ ] button to select, but i did, the others didn't, for example, remap 2.0.2 wasn't letting the L2 button be used and R2, but I tested it and managed to use the L2 and R2 button on it in Remap 2.0.2, but the plugin wasn't letting me use the L1 and R1 button, I tried it again on your plugin in ReVita, and it worked, you know, I'll do it a tutorial video and show it on YouTube, don't worry I'll say it was you who created it, thank you very much for making this plugin, oh and by the way I'm going to make a video in Portuguese, feel free to take my video and translate in English

**Comment by MERLev** [comment]
Glad it worked for you!
There is more info onto avaliable functionality on the [wiki](https://github.com/MERLev/reVita/wiki)
