### ISSUE TITLE
Crashing when exiting config menu

### ISSUE THREAD

**Issue by realNZZN** [MERLev/reVita#25]
When pressing circle to exit the config menu, the system crashes to a black screen and shuts down
Happens in all applications on psv2000 running henkaku 11 on 3.60 through enso

**Comment by MERLev** [comment]
Most likely you are using ds34vita. If so > pls update both reVita and ds34vita to latest versions? from github, not from autoplugin.

**Comment by realEnzeta** [comment]
That worked, was using an old version and thought it was a conflict with another plugin
