### ISSUE TITLE
reVita crashes when using ds34vita

### ISSUE THREAD

**Issue by MaixGit** [MERLev/reVita#26]
Without the plugin installed it works perfectly fine, but while ds34vita is installed, I can open the menu but when I try to exit the menu it crashes, it also instantly crashes when I try to open it in safe mode

**Comment by MERLev** [comment]
https://github.com/MERLev/reVita/issues/25
https://github.com/MERLev/reVita#known-issues

**Comment by MaixGit** [comment]
Thank you it worked.
Sorry for the inconvenience, I reinstalled both earlier but it didn't work that time, not sure why.

**Comment by MERLev** [comment]
Good to hear!
