### ISSUE TITLE
[Feature Suggestions] Enable/Disable Front/Back Touchscreen

### ISSUE THREAD

**Issue by jakerockz97** [MERLev/reVita#5]
In your old plugin RemaPsv2, there was an option like this if you remapped a Front/Back touchscreen, you can turn on or off the default input.

Can you add this back? and also if possible an option to enable and disable either front, back touchscreen(or both) in general with or without a remapped inputs set to them

**Comment by MERLev** [comment]
It's called "propagate", is toggled via TRIANGLE on Profile -> Remap Rules page.
