### ISSUE TITLE
Support for SCE_SYSTEM_PARAM_ENTER

### ISSUE THREAD

**Issue by strikersh** [MERLev/reVita#7]
Sony provide methods to detect which button is used as the enter button CROSS or CIRCLE.
A few games (most notably vanillware ones use it : dragon's crown, muramasa). It could be useful for those games (in muramasa jump and enter is on the same button if CROSS is used for example, which is somewhat frustrating).

I'm not sure if it should or not be part of this project
 docs :
https://docs.vitasdk.org/group__SceSystemParamUser.html#ga493dbfa2425f8adc558f4ec482f161af

**Comment by MERLev** [comment]
Added to 1.0.6 release under Profile > Compatibility > Enter/Cancel keys.
Requires app restart.
